# Generated by Django 5.0.4 on 2024-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=150)),
                ("color", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
        ),
    ]
